# Generated by Django 3.1.6 on 2021-02-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('powermove', models.TextField()),
                ('experience', models.IntegerField()),
                ('outOfOrder', models.BooleanField()),
                ('avatar', models.URLField()),
            ],
        ),
    ]
