# Generated by Django 3.1.6 on 2021-02-06 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robodanceapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DanceOff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dancedAt', models.DateTimeField(auto_now_add=True)),
                ('loser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loses', to='robodanceapi.robot')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wins', to='robodanceapi.robot')),
            ],
        ),
    ]
